# .github/workflows/ruby.yml
name: Ruby CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: "3.2" }
      - run: bundle install
      - run: bundle exec rake test
